sonata_admin:
    title: 'Symfony Training'
    security:
#        handler: sonata.admin.security.handler.role
#        role_admin: ROLE_ADMIN
    dashboard:
        groups:
            app.admin.group.content:
                label: User Admin
                label_catalogue: App
                items:
                    - app.admin.user
                    - app.admin.checklist
            app.admin.group.misc: ~
        blocks:
            - { type: sonata.admin.block.admin_list, position: center}

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

