services:
  app.admin.user:
    class: App\Admin\AdminControler
    arguments:
      - ~
      - App\Entity\User
      - ~
    tags:
      - name: sonata.admin
        manager_type: orm
        label: 'User'
        label_catalogue: 'App'
  app.admin.checklist:
    class: App\Admin\AdminChecklistControler
    arguments:
      - ~
      - App\Entity\Checklist
      - ~
    tags:
      - name: sonata.admin
        manager_type: orm
        label: 'Check list'
        label_catalogue: 'App'

